### PR TITLE
V4 Spec: getOrganizations

### PR DESCRIPTION
**Pull request by marians**
This PR contains the spec proposal for `GET /v4/organizations/`.

### CODE REVIEW

**Comment by oponder** [comment]
@marians I'm going to implement this now, are you happy with the way it's specced? Since you never put it up for review, is it still in progress?

I don't have any comment. It looks good to me. Including the bit about admin's being able to list all organizations

**Comment by marians** [comment]
@oponder The mechanics is still fine with me. Feel free to make this happen!

I'll change the description part a bit: This `The resulting list will contain all organizations the user is allowed to know about.` doesn't exactly make sense, as we every user is allows "to know" about an org's existence.

So for a normal user, the resulting list should contain all organizations the user is a member of.

For an admin, the list should simply contain all organizations.

**Comment by marians** [comment]
FYI @oponder: Merged master, updated spec

**Comment by oponder** [comment]
Thanks!

**Comment by oponder** [comment]
part of: https://github.com/giantswarm/api/issues/338

**Comment by oponder** [comment]
@marians: Technically your PR to merge. Listing orgs implementation is done

**Comment by marians** [comment]
Nice! 🎱

**Pull request merged**
