### PR TITLE
Allow set min nodepool to 0

### PR DESCRIPTION
**Pull request by paurosello**
Please make sure in case you are changing the spec all our customers are informed beforehand.

You can throw a message in #sig-customer with the changes and the Solution Engineers will take care of
sharing the changes with the customers.

### CODE REVIEW

**Comment by paurosello** [comment]
Towards https://github.com/giantswarm/roadmap/issues/234

**Review by calvix — APPROVED** [review]

**Review by xh3b4sd — APPROVED** [review]

**Review by pipo02mix — APPROVED** [review]

**Comment by marians** [comment]
Do we need `x-nullable` on the attribute to be able to accept an int value of zero?

**Comment by paurosello** [comment]
> Do we need `x-nullable` on the attribute to be able to accept an int value of zero?

Yup, not really intuitive but based on the research with Tim and the tests we did this is the only way

**Comment by marians** [comment]
Fine. Doesn't hurt from the API users perspective.

**Pull request merged**
