### PR TITLE
Remove the unnecessary mention of the V5 API being supported by AWS only

### PR DESCRIPTION
**Pull request by axbarsan**
This mention is no longer the case, and unnecessary, in my opinion. What do you think?

### CODE REVIEW

**Comment by whites11** [comment]
Maybe better to a specify KVM is not supported or that AWS and azure are supported?

**Comment by axbarsan** [comment]
But since platform support is so nicely displayed in the docs, does it make sense to copy-paste that info into the api spec, as well?

https://docs.giantswarm.io/basics/nodepools/

**Comment by whites11** [comment]
question: what happens if you call the API endpoint for KVM cluster? Does it fail in a clear way? Such as "node pools don't work on KVM"?

**Comment by tuommaki** [comment]
> question: what happens if you call the API endpoint for KVM cluster? Does it fail in a clear way? Such as "node pools don't work on KVM"?

Depends. Read/List operations most probably return 404 while other operations are clearer on that. E.g. cluster creation here:
https://github.com/giantswarm/api/blob/master/service/cluster/creator/service.go#L207

**Comment by tuommaki** [comment]
> does it make sense to copy-paste that info into the api spec, as well?

I don't think so. `api-spec` specifies the API available. Documentation specifies which provider supports which features. Bad analogy: You buy a mechanic's tool (e.g. torque wrench) which is accompanied with manual how to use it. It doesn't describe products you can use it on (nails?).

**Review by tuommaki — APPROVED** [review]

**Pull request merged**
