### PR TITLE
Spec/docs for scaling clusters (adding/removing cluster nodes)

### PR DESCRIPTION
**Pull request by marians**
For https://github.com/giantswarm/api-spec/issues/24

### CODE REVIEW

**Comment by oponder** [comment]
Should we have some mention in here that when creating / scaling aws nodes, they must be all of the same instance type?

**Comment by rossf7** [comment]
I think it would be good to mention it. We can remove once `aws-operator` supports multiple instance types for workers.

**Comment by marians** [comment]
> Should we have some mention in here that when creating / scaling aws nodes, they must be all of the same instance type?

That's not what I understood. I understood that we create one Auto Scaling Group per instance type. If the user has three nodes already with three different instance types and adds a fourth node now with yet a different instance type, it should still work. Right?

**Comment by puja108** [comment]
The first step will be a single ASG (so limit to 1 instance type), next will be ASG per instance type, the single ASG/instance is only a minor step in between

**Comment by oponder** [comment]
I guess it depends on when we want to merge and publish this spec.

**Comment by marians** [comment]
Excuse me, yes. I could have looked at my notes...

We should merge this ASAP, so of course I'll change it to inform about the restriction.

**Comment by marians** [comment]
Content is now updated. If you like, please re-check.

**Comment by marians** [comment]
Damn, I shouldn't have merged this already, as it isn't implemented yet...

**Comment by marians** [comment]
Reverting this PR merge in https://github.com/giantswarm/api-spec/issues/33

**Pull request merged**
