### PR TITLE
Remove 404 error code from reset password request

### PR DESCRIPTION
**Pull request by axbarsan**
Related to https://github.com/giantswarm/giantswarm/issues/4248

### CODE REVIEW

**Comment by axbarsan** [comment]
Decided to close based on https://github.com/giantswarm/api/pull/983

**Comment by oponder** [comment]
Arguably this is a security improvement and not a new feature. So I wouldn't be against implementing it!

**Comment by axbarsan** [comment]
> Arguably this is a security improvement and not a new feature. So I wouldn't be against implementing it!

👍 Reopened based on this

**Comment by axbarsan** [comment]
Closed because of problem misunderstanding. Solution should be in the `passage` service

**Comment by oponder** [comment]
Sorry for not noticing it earlier :P

**Pull request closed without merging**
